"""empty message

Revision ID: 3655abe23c8c
Revises: 
Create Date: 2021-08-18 05:55:10.008736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3655abe23c8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movie',
    sa.Column('movie_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('popularity', sa.Float(), nullable=False),
    sa.Column('director', sa.String(length=500), nullable=True),
    sa.Column('imdb_score', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('moviegenre',
    sa.Column('movie_genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_name', sa.String(length=500), nullable=True),
    sa.Column('genre_name', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['genre_name'], ['genre.name'], ),
    sa.ForeignKeyConstraint(['movie_name'], ['movie.name'], ),
    sa.PrimaryKeyConstraint('movie_genre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moviegenre')
    op.drop_table('user')
    op.drop_table('movie')
    op.drop_table('genre')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
